from typing import Protocol


class TokenCreator(Protocol):
    async def create_refresh_token(self, user_id: str) -> str: ...
    async def create_access_token(self, user_id: str) -> str: ...
    async def verify_refresh_token(self, token: str) -> str: ...
