services:
  frontend:
    volumes:
      - ./frontend/nginx/local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  backend:
    ports:
      - "8080:8080"

  db:
    ports:
      - "5432:5432"
