version: "3.8"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend/src/infrastructure/db/alembic:/app/backend/src/infrastructure/db/alembic


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
