"""tables for oauth

Revision ID: 0c2a50b66130
Revises: 92b85e82f5af
Create Date: 2025-09-10 14:57:30.634756

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2a50b66130'
down_revision: Union[str, Sequence[str], None] = '92b85e82f5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauthaccountsdb',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('usersdb', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersdb', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usersdb', 'tg_nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usersdb', 'tg_nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersdb', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usersdb', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('oauthaccountsdb')
    # ### end Alembic commands ###
