"""cascade delete for participant

Revision ID: 543c13a47384
Revises: ee3252007069
Create Date: 2025-08-28 18:06:49.609475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543c13a47384'
down_revision: Union[str, Sequence[str], None] = 'ee3252007069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teamsdb', 'teamlead_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('teamsdb_teamlead_id_fkey'), 'teamsdb', type_='foreignkey')
    op.create_foreign_key(None, 'teamsdb', 'participantsdb', ['teamlead_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teamsdb', type_='foreignkey')
    op.create_foreign_key(op.f('teamsdb_teamlead_id_fkey'), 'teamsdb', 'participantsdb', ['teamlead_id'], ['id'])
    op.alter_column('teamsdb', 'teamlead_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
