"""another one fix cascade delete for teams

Revision ID: 92b85e82f5af
Revises: 00b0aa3e82f9
Create Date: 2025-08-28 18:19:04.154698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b85e82f5af'
down_revision: Union[str, Sequence[str], None] = '00b0aa3e82f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teammembersdb', 'team_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teammembersdb', 'participant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('teammembersdb_participant_id_fkey'), 'teammembersdb', type_='foreignkey')
    op.drop_constraint(op.f('teammembersdb_team_id_fkey'), 'teammembersdb', type_='foreignkey')
    op.create_foreign_key(None, 'teammembersdb', 'participantsdb', ['participant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teammembersdb', 'teamsdb', ['team_id'], ['id'], ondelete='CASCADE')
    op.alter_column('teamvacanciesdb', 'team_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('teamvacanciesdb_team_id_fkey'), 'teamvacanciesdb', type_='foreignkey')
    op.create_foreign_key(None, 'teamvacanciesdb', 'teamsdb', ['team_id'], ['id'], ondelete='CASCADE')
    op.alter_column('teamvacanciesskillsdb', 'vacancy_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('teamvacanciesskillsdb_vacancy_id_fkey'), 'teamvacanciesskillsdb', type_='foreignkey')
    op.create_foreign_key(None, 'teamvacanciesskillsdb', 'teamvacanciesdb', ['vacancy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teamvacanciesskillsdb', type_='foreignkey')
    op.create_foreign_key(op.f('teamvacanciesskillsdb_vacancy_id_fkey'), 'teamvacanciesskillsdb', 'teamvacanciesdb', ['vacancy_id'], ['id'])
    op.alter_column('teamvacanciesskillsdb', 'vacancy_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'teamvacanciesdb', type_='foreignkey')
    op.create_foreign_key(op.f('teamvacanciesdb_team_id_fkey'), 'teamvacanciesdb', 'teamsdb', ['team_id'], ['id'])
    op.alter_column('teamvacanciesdb', 'team_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'teammembersdb', type_='foreignkey')
    op.drop_constraint(None, 'teammembersdb', type_='foreignkey')
    op.create_foreign_key(op.f('teammembersdb_team_id_fkey'), 'teammembersdb', 'teamsdb', ['team_id'], ['id'])
    op.create_foreign_key(op.f('teammembersdb_participant_id_fkey'), 'teammembersdb', 'participantsdb', ['participant_id'], ['id'])
    op.alter_column('teammembersdb', 'participant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teammembersdb', 'team_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
