"""is_active field in eventsdb add

Revision ID: ca042ce62874
Revises: 0c2a50b66130
Create Date: 2025-12-29 10:31:32.152421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca042ce62874'
down_revision: Union[str, Sequence[str], None] = '0c2a50b66130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('eventsdb', sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()))

    op.execute("UPDATE eventsdb SET is_active = TRUE WHERE is_active IS NULL")

    op.alter_column('eventsdb', 'is_active', nullable=False, server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventsdb', 'is_active')
    # ### end Alembic commands ###
